### PR TITLE
mutex: throw system_error when constuctor failed and lock failed

### LINKED ISSUE #645: bthread::Mutex 静默初始化失败的疑问
使用 brpc 的程序出 core，发现是一个 bthread::Mutex 内部的 butex 为空指针，追溯发现在 bthread::Mutex 的构造函数中，如果 bthread_mutex_init 返回空指针，只会打日志，不会向外报出错误。为何要这样设计呢？

另外，在何状态下会导致 bthread_mutex_init 返回空指针呢？

### PR DESCRIPTION
**Pull request by choleraehyq**
Fix #645 

Signed-off-by: Cholerae Hu <choleraehyq@gmail.com>

### CODE REVIEW

File: src/bthread/mutex.h [hunk 1]
```diff
@@ -42,11 +42,21 @@ namespace bthread {
...
     native_handler_type native_handler() { return &_mutex; }
-    void lock() { bthread_mutex_lock(&_mutex); }
-    void unlock() { bthread_mutex_unlock(&_mutex); }
+    void lock() {
+        int ec = bthread_mutex_lock(&_mutex);
+        if (ec != 0) {
+            throw std::system_error(std::error_code(ec, std::system_category()), "Mutex lock failed");
+        }
+    }
+    void unlock() { CHECK_EQ(0, bthread_mutex_unlock(&_mutex)); }
```
Comment (jamesge) [inline src/bthread/mutex.h]: 这个出问题时可能会刷屏的，不要加了。

Comment (choleraehyq) [reply src/bthread/mutex.h]: done
